# Generated by Django 2.1.2 on 2019-03-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190209_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('other', 'other'), ('coats', 'coats'), ('bras', 'bras'), ('pants', 'pants'), ('wallets', 'wallets'), ('socks', 'socks'), ('loafers', 'loafers'), ('suits', 'suits'), ('Hoodies-and-Zipups', 'Hoodies-and-Zipups'), ('sweatpants', 'sweatpants'), ('t-shirt', 't-shirt'), ('cardigans', 'cardigans'), ('sneakers', 'sneakers'), ('joggers', 'joggers'), ('trousers', 'trousers'), ('polo', 'polo'), ('boxers', 'boxers'), ('hats', 'hats'), ('dress-shirt', 'dress-shirt'), ('thongs', 'thongs'), ('gloves', 'gloves'), ('blazers', 'blazers'), ('vests', 'vests'), ('crewnecks', 'crewnecks'), ('jeans', 'jeans'), ('briefs', 'briefs'), ('turtlenecks', 'turtlenecks'), ('bombers', 'bombers'), ('long-sleeves', 'long-sleeves'), ('dress-pants', 'dress-pants'), ('eyewear', 'eyewear'), ('jewelry', 'jewelry'), ('jackets', 'jackets'), ('backpacks', 'backpacks'), ('corsets-and-bodysuits', 'corsets-and-bodysuits'), ('scarves', 'scarves'), ('formal-wear', 'formal-wear'), ('sweatshirts', 'sweatshirts'), ('belts', 'belts'), ('tank-tops', 'tank-tops'), ('shorts', 'shorts')], max_length=300, null=True),
        ),
    ]
