# Generated by Django 2.1.2 on 2019-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190320_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('boxers', 'boxers'), ('vests', 'vests'), ('thongs', 'thongs'), ('bras', 'bras'), ('gloves', 'gloves'), ('dress-shirt', 'dress-shirt'), ('sweatshirts', 'sweatshirts'), ('scarves', 'scarves'), ('backpacks', 'backpacks'), ('suits', 'suits'), ('joggers', 'joggers'), ('crewnecks', 'crewnecks'), ('pants', 'pants'), ('cardigans', 'cardigans'), ('blazers', 'blazers'), ('tank-tops', 'tank-tops'), ('jackets', 'jackets'), ('shorts', 'shorts'), ('belts', 'belts'), ('eyewear', 'eyewear'), ('jeans', 'jeans'), ('sweatpants', 'sweatpants'), ('other', 'other'), ('polo', 'polo'), ('loafers', 'loafers'), ('formal-wear', 'formal-wear'), ('turtlenecks', 'turtlenecks'), ('t-shirt', 't-shirt'), ('jewelry', 'jewelry'), ('corsets-and-bodysuits', 'corsets-and-bodysuits'), ('briefs', 'briefs'), ('sneakers', 'sneakers'), ('bombers', 'bombers'), ('hats', 'hats'), ('wallets', 'wallets'), ('long-sleeves', 'long-sleeves'), ('trousers', 'trousers'), ('socks', 'socks'), ('dress-pants', 'dress-pants'), ('Hoodies-and-Zipups', 'Hoodies-and-Zipups'), ('coats', 'coats')], max_length=300, null=True),
        ),
    ]
